//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yudin203.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_YudinEntities2 : DbContext
    {
        private static Bd_YudinEntities2 _context;
        public Bd_YudinEntities2()
            : base("name=Bd_YudinEntities2")
        {
        }
        public static Bd_YudinEntities2 GetContext()
        {
            if (_context == null) 
            _context = new Bd_YudinEntities2();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoriya> Kategoriya { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
