//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yudin203.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public string Artikul { get; set; }
        public string Nazvanie { get; set; }
        public string Izmerenie { get; set; }
        public int Stoimost { get; set; }
        public Nullable<int> Max_skidka { get; set; }
        public string Proizvoditel { get; set; }
        public string Postavshik { get; set; }
        public int Kategoriya { get; set; }
        public Nullable<int> Deistvuyushaya_skidka { get; set; }
        public Nullable<int> Kolvo_na_sklade { get; set; }
        public string Opisanie { get; set; }
        public string Izobrazhenie { get; set; }
    
        public virtual Kategoriya Kategoriya1 { get; set; }
    }
}
