//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yudin203.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int code { get; set; }
        public string familiya { get; set; }
        public string ImyaOtchestvo { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
        public int codeRole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
